// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"nof0-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: HealthzHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/readyz",
				Handler: ReadyzHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/metrics",
				Handler: MetricsHandler(),
			},
			{
				Method:  http.MethodGet,
				Path:    "/debug/vars",
				Handler: MetricsHandler(),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/account-totals",
				Handler: AccountTotalsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/analytics",
				Handler: AnalyticsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/analytics/:modelId",
				Handler: ModelAnalyticsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/crypto-prices",
				Handler: CryptoPricesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/leaderboard",
				Handler: LeaderboardHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/since-inception-values",
				Handler: SinceInceptionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/trades",
				Handler: TradesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/positions",
				Handler: PositionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/conversations",
				Handler: ConversationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/traders",
				Handler: TradersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/traders/:traderId",
				Handler: TraderDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/traders/:traderId/status",
				Handler: TraderStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/audit-events",
				Handler: AuditEventsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/orders",
				Handler: OrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/traders/:traderId/start",
				Handler: TraderStartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/traders/:traderId/stop",
				Handler: TraderStopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/traders/:traderId/pause",
				Handler: TraderPauseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/traders/:traderId/resume",
				Handler: TraderResumeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/decisions/:decisionId/approve",
				Handler: DecisionApproveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/decisions/:decisionId/reject",
				Handler: DecisionRejectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/preview",
				Handler: OrderPreviewHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/:orderId/approve",
				Handler: OrderApproveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders/:orderId/reject",
				Handler: OrderRejectHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
