// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Position struct {
	EntryOid         int64       `json:"entry_oid"`
	RiskUsd          float64     `json:"risk_usd"`
	Confidence       float64     `json:"confidence"`
	IndexCol         interface{} `json:"index_col"`
	ExitPlan         interface{} `json:"exit_plan"`
	EntryTime        float64     `json:"entry_time"`
	Symbol           string      `json:"symbol"`
	EntryPrice       float64     `json:"entry_price"`
	TpOid            int64       `json:"tp_oid"`
	Margin           float64     `json:"margin"`
	WaitForFill      bool        `json:"wait_for_fill"`
	SlOid            int64       `json:"sl_oid"`
	Oid              int64       `json:"oid"`
	CurrentPrice     float64     `json:"current_price"`
	ClosedPnl        float64     `json:"closed_pnl"`
	LiquidationPrice float64     `json:"liquidation_price"`
	Commission       float64     `json:"commission"`
	Leverage         float64     `json:"leverage"`
	Slippage         float64     `json:"slippage"`
	Quantity         float64     `json:"quantity"`
	UnrealizedPnl    float64     `json:"unrealized_pnl"`
}

type AccountTotal struct {
	Id                         string              `json:"id"`
	ModelId                    string              `json:"model_id"`
	Timestamp                  float64             `json:"timestamp"`
	DollarEquity               float64             `json:"dollar_equity"`
	RealizedPnl                float64             `json:"realized_pnl"`
	TotalUnrealizedPnl         float64             `json:"total_unrealized_pnl"`
	CumPnlPct                  float64             `json:"cum_pnl_pct"`
	SharpeRatio                float64             `json:"sharpe_ratio"`
	SinceInceptionHourlyMarker int                 `json:"since_inception_hourly_marker"`
	SinceInceptionMinuteMarker int                 `json:"since_inception_minute_marker"`
	Positions                  map[string]Position `json:"positions"`
}

type AccountTotalsRequest struct {
	LastHourlyMarker int `form:"lastHourlyMarker,optional"`
}

type AccountTotalsResponse struct {
	AccountTotals        []AccountTotal `json:"accountTotals"`
	LastHourlyMarkerRead int            `json:"lastHourlyMarkerRead"`
	ServerTime           int64          `json:"serverTime"`
}

type AccountValue struct {
	Timestamp int64   `json:"timestamp"`
	Value     float64 `json:"value"`
}

type AnalyticsResponse struct {
	Analytics  []ModelAnalytics `json:"analytics"`
	ServerTime int64            `json:"serverTime"`
}

type BreakdownTable struct {
	StdNetPnl                  float64 `json:"std_net_pnl,omitempty"`
	TotalFeesPaid              float64 `json:"total_fees_paid,omitempty"`
	OverallPnlWithoutFees      float64 `json:"overall_pnl_without_fees,omitempty"`
	TotalFeesAsPctOfPnl        float64 `json:"total_fees_as_pct_of_pnl,omitempty"`
	OverallPnlWithFees         float64 `json:"overall_pnl_with_fees,omitempty"`
	AvgTakerFee                float64 `json:"avg_taker_fee,omitempty"`
	StdGrossPnl                float64 `json:"std_gross_pnl,omitempty"`
	AvgNetPnl                  float64 `json:"avg_net_pnl,omitempty"`
	BiggestNetLoss             float64 `json:"biggest_net_loss,omitempty"`
	BiggestNetGain             float64 `json:"biggest_net_gain,omitempty"`
	AvgGrossPnl                float64 `json:"avg_gross_pnl,omitempty"`
	StdTakerFee                float64 `json:"std_taker_fee,omitempty"`
	StdLosersNotional          float64 `json:"std_losers_notional,omitempty"`
	StdWinnersNotional         float64 `json:"std_winners_notional,omitempty"`
	AvgWinnersNetPnl           float64 `json:"avg_winners_net_pnl,omitempty"`
	WinRate                    float64 `json:"win_rate,omitempty"`
	StdLosersNetPnl            float64 `json:"std_losers_net_pnl,omitempty"`
	AvgLosersNetPnl            float64 `json:"avg_losers_net_pnl,omitempty"`
	StdLosersHoldingPeriod     float64 `json:"std_losers_holding_period,omitempty"`
	AvgLosersNotional          float64 `json:"avg_losers_notional,omitempty"`
	AvgLosersHoldingPeriod     float64 `json:"avg_losers_holding_period,omitempty"`
	AvgWinnersHoldingPeriod    float64 `json:"avg_winners_holding_period,omitempty"`
	StdWinnersNetPnl           float64 `json:"std_winners_net_pnl,omitempty"`
	AvgWinnersNotional         float64 `json:"avg_winners_notional,omitempty"`
	StdWinnersHoldingPeriod    float64 `json:"std_winners_holding_period,omitempty"`
	StdLongsHoldingPeriod      float64 `json:"std_longs_holding_period,omitempty"`
	StdLongsNotional           float64 `json:"std_longs_notional,omitempty"`
	StdShortsNotional          float64 `json:"std_shorts_notional,omitempty"`
	NumLongTrades              int     `json:"num_long_trades,omitempty"`
	AvgLongsNotional           float64 `json:"avg_longs_notional,omitempty"`
	AvgShortsHoldingPeriod     float64 `json:"avg_shorts_holding_period,omitempty"`
	AvgShortsNetPnl            float64 `json:"avg_shorts_net_pnl,omitempty"`
	AvgLongsNetPnl             float64 `json:"avg_longs_net_pnl,omitempty"`
	StdShortsHoldingPeriod     float64 `json:"std_shorts_holding_period,omitempty"`
	NumShortTrades             int     `json:"num_short_trades,omitempty"`
	LongShortTradesRatio       float64 `json:"long_short_trades_ratio,omitempty"`
	StdShortsNetPnl            float64 `json:"std_shorts_net_pnl,omitempty"`
	AvgLongsHoldingPeriod      float64 `json:"avg_longs_holding_period,omitempty"`
	StdLongsNetPnl             float64 `json:"std_longs_net_pnl,omitempty"`
	AvgShortsNotional          float64 `json:"avg_shorts_notional,omitempty"`
	NumShortSignals            int     `json:"num_short_signals,omitempty"`
	AvgConfidenceClose         float64 `json:"avg_confidence_close,omitempty"`
	AvgLeverageLong            float64 `json:"avg_leverage_long,omitempty"`
	StdLeverage                float64 `json:"std_leverage,omitempty"`
	PctMinsFlatCombined        float64 `json:"pct_mins_flat_combined,omitempty"`
	NumCloseSignals            int     `json:"num_close_signals,omitempty"`
	MinsLongCombined           float64 `json:"mins_long_combined,omitempty"`
	StdConfidence              float64 `json:"std_confidence,omitempty"`
	LongSignalPct              float64 `json:"long_signal_pct,omitempty"`
	MinsShortCombined          float64 `json:"mins_short_combined,omitempty"`
	NumHoldSignals             int     `json:"num_hold_signals,omitempty"`
	StdConfidenceShort         float64 `json:"std_confidence_short,omitempty"`
	AvgLeverage                float64 `json:"avg_leverage,omitempty"`
	MedianLeverage             float64 `json:"median_leverage,omitempty"`
	HoldSignalPct              float64 `json:"hold_signal_pct,omitempty"`
	CloseSignalPct             float64 `json:"close_signal_pct,omitempty"`
	AvgConfidenceLong          float64 `json:"avg_confidence_long,omitempty"`
	AvgConfidence              float64 `json:"avg_confidence,omitempty"`
	MedianConfidence           float64 `json:"median_confidence,omitempty"`
	TotalSignals               int     `json:"total_signals,omitempty"`
	ShortSignalPct             float64 `json:"short_signal_pct,omitempty"`
	StdLeverageLong            float64 `json:"std_leverage_long,omitempty"`
	NumLongSignals             int     `json:"num_long_signals,omitempty"`
	LongShortRatio             float64 `json:"long_short_ratio,omitempty"`
	PctMinsShortCombined       float64 `json:"pct_mins_short_combined,omitempty"`
	StdConfidenceHold          float64 `json:"std_confidence_hold,omitempty"`
	MinsFlatCombined           float64 `json:"mins_flat_combined,omitempty"`
	StdLeverageShort           float64 `json:"std_leverage_short,omitempty"`
	StdConfidenceLong          float64 `json:"std_confidence_long,omitempty"`
	AvgConfidenceHold          float64 `json:"avg_confidence_hold,omitempty"`
	AvgConfidenceShort         float64 `json:"avg_confidence_short,omitempty"`
	StdConfidenceClose         float64 `json:"std_confidence_close,omitempty"`
	AvgLeverageShort           float64 `json:"avg_leverage_short,omitempty"`
	PctMinsLongCombined        float64 `json:"pct_mins_long_combined,omitempty"`
	MaxInvocationBreakMins     float64 `json:"max_invocation_break_mins,omitempty"`
	StdInvocationBreakMins     float64 `json:"std_invocation_break_mins,omitempty"`
	NumInvocations             int     `json:"num_invocations,omitempty"`
	MinInvocationBreakMins     float64 `json:"min_invocation_break_mins,omitempty"`
	AvgInvocationBreakMins     float64 `json:"avg_invocation_break_mins,omitempty"`
	AvgConvoLeverage           float64 `json:"avg_convo_leverage,omitempty"`
	AvgHoldingPeriodMins       float64 `json:"avg_holding_period_mins,omitempty"`
	AvgTakeProfitDistancePct   float64 `json:"avg_take_profit_distance_pct,omitempty"`
	MedianHoldingPeriodMins    float64 `json:"median_holding_period_mins,omitempty"`
	StdSizeOfTradeNotional     float64 `json:"std_size_of_trade_notional,omitempty"`
	AvgSizeOfTradeNotional     float64 `json:"avg_size_of_trade_notional,omitempty"`
	TotalTrades                int     `json:"total_trades,omitempty"`
	MedianSizeOfTradeNotional  float64 `json:"median_size_of_trade_notional,omitempty"`
	AvgSizeOfTradePortfolioPct float64 `json:"avg_size_of_trade_portfolio_pct,omitempty"`
	StdHoldingPeriodMins       float64 `json:"std_holding_period_mins,omitempty"`
	AvgStopLossDistancePct     float64 `json:"avg_stop_loss_distance_pct,omitempty"`
	StdSizeOfTradePortfolioPct float64 `json:"std_size_of_trade_portfolio_pct,omitempty"`
	MedianConvoLeverage        float64 `json:"median_convo_leverage,omitempty"`
}

type CryptoPrice struct {
	Symbol    string  `json:"symbol"`
	Price     float64 `json:"price"`
	Timestamp int64   `json:"timestamp"`
}

type CryptoPricesResponse struct {
	Prices     map[string]CryptoPrice `json:"prices"`
	ServerTime int64                  `json:"serverTime"`
}

type LeaderboardEntry struct {
	Id          string  `json:"id"`
	NumTrades   int     `json:"num_trades"`
	Sharpe      float64 `json:"sharpe"`
	WinDollars  float64 `json:"win_dollars"`
	NumLosses   int     `json:"num_losses"`
	LoseDollars float64 `json:"lose_dollars"`
	ReturnPct   float64 `json:"return_pct"`
	Equity      float64 `json:"equity"`
	NumWins     int     `json:"num_wins"`
}

type LeaderboardResponse struct {
	Leaderboard []LeaderboardEntry `json:"leaderboard"`
}

type ModelAnalytics struct {
	Id                          string         `json:"id"`
	ModelId                     string         `json:"model_id"`
	UpdatedAt                   float64        `json:"updated_at"`
	FeePnlMovesBreakdownTable   BreakdownTable `json:"fee_pnl_moves_breakdown_table"`
	WinnersLosersBreakdownTable BreakdownTable `json:"winners_losers_breakdown_table"`
	SignalsBreakdownTable       BreakdownTable `json:"signals_breakdown_table"`
	LastTradeExitTime           float64        `json:"last_trade_exit_time"`
	InvocationBreakdownTable    BreakdownTable `json:"invocation_breakdown_table"`
	LongsShortsBreakdownTable   BreakdownTable `json:"longs_shorts_breakdown_table"`
	LastConvoDocId              string         `json:"last_convo_doc_id"`
	LastConvoTimestamp          float64        `json:"last_convo_timestamp"`
	OverallTradesOverviewTable  BreakdownTable `json:"overall_trades_overview_table"`
	LastTradeDocId              string         `json:"last_trade_doc_id"`
}

type ModelAnalyticsResponse struct {
	Analytics  ModelAnalytics `json:"analytics"`
	ServerTime int64          `json:"serverTime"`
}

type SinceInceptionValue struct {
	Id                string  `json:"id"`
	NavSinceInception float64 `json:"nav_since_inception"`
	InceptionDate     float64 `json:"inception_date"`
	NumInvocations    int     `json:"num_invocations"`
	ModelId           string  `json:"model_id"`
}

type SinceInceptionResponse struct {
	SinceInceptionValues []SinceInceptionValue `json:"sinceInceptionValues"`
	ServerTime           int64                 `json:"serverTime"`
}

type Trade struct {
	Id                     string      `json:"id"`
	ModelId                string      `json:"model_id"`
	Symbol                 string      `json:"symbol"`
	Side                   string      `json:"side"`
	TradeType              string      `json:"trade_type"`
	TradeId                string      `json:"trade_id"`
	Quantity               float64     `json:"quantity"`
	Leverage               float64     `json:"leverage"`
	Confidence             float64     `json:"confidence"`
	EntryPrice             float64     `json:"entry_price"`
	EntryTime              float64     `json:"entry_time"`
	EntryHumanTime         string      `json:"entry_human_time"`
	EntrySz                float64     `json:"entry_sz"`
	EntryTid               int64       `json:"entry_tid"`
	EntryOid               int64       `json:"entry_oid"`
	EntryCrossed           bool        `json:"entry_crossed"`
	EntryLiquidation       interface{} `json:"entry_liquidation"`
	EntryCommissionDollars float64     `json:"entry_commission_dollars"`
	EntryClosedPnl         float64     `json:"entry_closed_pnl"`
	ExitPrice              float64     `json:"exit_price"`
	ExitTime               float64     `json:"exit_time"`
	ExitHumanTime          string      `json:"exit_human_time"`
	ExitSz                 float64     `json:"exit_sz"`
	ExitTid                int64       `json:"exit_tid"`
	ExitOid                int64       `json:"exit_oid"`
	ExitCrossed            bool        `json:"exit_crossed"`
	ExitLiquidation        interface{} `json:"exit_liquidation"`
	ExitCommissionDollars  float64     `json:"exit_commission_dollars"`
	ExitClosedPnl          float64     `json:"exit_closed_pnl"`
	ExitPlan               interface{} `json:"exit_plan"`
	RealizedGrossPnl       float64     `json:"realized_gross_pnl"`
	RealizedNetPnl         float64     `json:"realized_net_pnl"`
	TotalCommissionDollars float64     `json:"total_commission_dollars"`
}

type TradesResponse struct {
	Trades     []Trade `json:"trades"`
	ServerTime int64   `json:"serverTime"`
}

type TradesRequest struct {
	TraderId string `form:"trader_id,optional"`
	Symbol   string `form:"symbol,optional"`
	Side     string `form:"side,optional"`
	Limit    int    `form:"limit,optional,default=100"`
	Offset   int    `form:"offset,optional,default=0"`
}

type PositionsRequest struct {
	TraderId string `form:"trader_id,optional"`
	Symbol   string `form:"symbol,optional"`
	Status   string `form:"status,optional,default=open"`
	Limit    int    `form:"limit,optional,default=1000"`
	Offset   int    `form:"offset,optional,default=0"`
}

type PositionsByModel struct {
	ModelId   string              `json:"model_id"`
	Positions map[string]Position `json:"positions"`
}

type PositionsResponse struct {
	AccountTotals []PositionsByModel `json:"accountTotals"`
	ServerTime    int64              `json:"serverTime"`
}

type ConversationMessage struct {
	Role      string      `json:"role"`
	Content   string      `json:"content"`
	Timestamp interface{} `json:"timestamp,omitempty"`
}

type Conversation struct {
	ModelId  string                `json:"model_id"`
	Messages []ConversationMessage `json:"messages"`
}

type ConversationsResponse struct {
	Conversations []Conversation `json:"conversations"`
	ServerTime    int64          `json:"serverTime"`
}

type ListMeta struct {
	Limit      int    `json:"limit"`
	Offset     int    `json:"offset"`
	Count      int    `json:"count"`
	NextOffset int    `json:"next_offset,omitempty"`
	Source     string `json:"source,omitempty"`
}

type TraderRiskParams struct {
	MaxPositions       int     `json:"max_positions"`
	MaxPositionSizeUsd float64 `json:"max_position_size_usd"`
	MaxMarginUsagePct  float64 `json:"max_margin_usage_pct"`
	MajorCoinLeverage  int     `json:"major_coin_leverage"`
	AltcoinLeverage    int     `json:"altcoin_leverage"`
	MinRiskRewardRatio float64 `json:"min_risk_reward_ratio"`
	MinConfidence      int     `json:"min_confidence"`
	StopLossEnabled    bool    `json:"stop_loss_enabled"`
	TakeProfitEnabled  bool    `json:"take_profit_enabled"`
}

type TraderExecGuards struct {
	MaxNewPositionsPerCycle int     `json:"max_new_positions_per_cycle"`
	LiquidityThresholdUsd   float64 `json:"liquidity_threshold_usd"`
	MaxMarginUsagePct       float64 `json:"max_margin_usage_pct"`
	CooldownAfterClose      string  `json:"cooldown_after_close"`
	PauseDurationOnBreach   string  `json:"pause_duration_on_breach"`
}

type TraderStatus struct {
	TraderId            string      `json:"trader_id"`
	Status              string      `json:"status"`
	IsRunning           bool        `json:"is_running"`
	ActiveConfigVersion int64       `json:"active_config_version"`
	LastDecisionAt      string      `json:"last_decision_at,omitempty"`
	NextDecisionAt      string      `json:"next_decision_at,omitempty"`
	PausedUntil         string      `json:"paused_until,omitempty"`
	PauseReason         string      `json:"pause_reason,omitempty"`
	UpdatedAt           string      `json:"updated_at,omitempty"`
	Detail              interface{} `json:"detail,omitempty"`
}

type TraderSummary struct {
	Id               string       `json:"id"`
	Name             string       `json:"name"`
	Model            string       `json:"model"`
	ExchangeProvider string       `json:"exchange_provider"`
	MarketProvider   string       `json:"market_provider"`
	ExecutionMode    string       `json:"execution_mode"`
	OrderStyle       string       `json:"order_style"`
	AllocationPct    float64      `json:"allocation_pct"`
	AutoStart        bool         `json:"auto_start"`
	Status           TraderStatus `json:"status"`
}

type TraderDetail struct {
	Id                   string           `json:"id"`
	Name                 string           `json:"name"`
	Model                string           `json:"model"`
	ExchangeProvider     string           `json:"exchange_provider"`
	MarketProvider       string           `json:"market_provider"`
	ExecutionMode        string           `json:"execution_mode"`
	OrderStyle           string           `json:"order_style"`
	MarketIocSlippageBps float64          `json:"market_ioc_slippage_bps"`
	DecisionInterval     string           `json:"decision_interval"`
	AllocationPct        float64          `json:"allocation_pct"`
	AutoStart            bool             `json:"auto_start"`
	JournalEnabled       bool             `json:"journal_enabled"`
	RiskParams           TraderRiskParams `json:"risk_params"`
	ExecGuards           TraderExecGuards `json:"exec_guards"`
	Status               TraderStatus     `json:"status"`
	PromptDigest         string           `json:"prompt_digest,omitempty"`
}

type TradersRequest struct {
	Status        string `form:"status,optional"`
	ExecutionMode string `form:"execution_mode,optional"`
	Limit         int    `form:"limit,optional,default=100"`
	Offset        int    `form:"offset,optional,default=0"`
}

type TraderPathRequest struct {
	TraderId string `path:"traderId"`
}

type TradersResponse struct {
	Traders      []TraderSummary `json:"traders"`
	Meta         ListMeta        `json:"meta"`
	ServerTimeMs int64           `json:"server_time_ms"`
}

type TraderResponse struct {
	Trader       TraderDetail `json:"trader"`
	ServerTimeMs int64        `json:"server_time_ms"`
}

type TraderStatusResponse struct {
	Status       TraderStatus `json:"status"`
	ServerTimeMs int64        `json:"server_time_ms"`
}

type AuditEventsRequest struct {
	TraderId             string `form:"trader_id,optional"`
	Type                 string `form:"type,optional"`
	CorrelationId        string `form:"correlation_id,optional"`
	CreatedAfterRfc3339  string `form:"created_after_rfc3339,optional"`
	CreatedBeforeRfc3339 string `form:"created_before_rfc3339,optional"`
	Limit                int    `form:"limit,optional,default=100"`
	Offset               int    `form:"offset,optional,default=0"`
}

type AuditEvent struct {
	Id              int64       `json:"id"`
	Type            string      `json:"type"`
	TraderId        string      `json:"trader_id"`
	CycleId         int64       `json:"cycle_id,omitempty"`
	CorrelationId   string      `json:"correlation_id,omitempty"`
	Symbol          string      `json:"symbol,omitempty"`
	Action          string      `json:"action,omitempty"`
	ModelId         string      `json:"model_id,omitempty"`
	ModelName       string      `json:"model_name,omitempty"`
	PromptDigest    string      `json:"prompt_digest,omitempty"`
	ApprovalTokenId string      `json:"approval_token_id,omitempty"`
	Reason          string      `json:"reason,omitempty"`
	Error           string      `json:"error,omitempty"`
	Detail          interface{} `json:"detail,omitempty"`
	CreatedAt       string      `json:"created_at"`
}

type AuditEventsResponse struct {
	Events       []AuditEvent `json:"events"`
	Meta         ListMeta     `json:"meta"`
	ServerTimeMs int64        `json:"server_time_ms"`
}

type OrdersRequest struct {
	TraderId string `form:"trader_id,optional"`
	Symbol   string `form:"symbol,optional"`
	Status   string `form:"status,optional"`
	Limit    int    `form:"limit,optional,default=100"`
	Offset   int    `form:"offset,optional,default=0"`
}

type Order struct {
	Id            string      `json:"id,optional"`
	TraderId      string      `json:"trader_id,optional"`
	Symbol        string      `json:"symbol"`
	Side          string      `json:"side"`
	Type          string      `json:"type"`
	Status        string      `json:"status,optional"`
	Quantity      float64     `json:"quantity"`
	LimitPrice    float64     `json:"limit_price,optional"`
	CreatedAt     string      `json:"created_at,optional"`
	UpdatedAt     string      `json:"updated_at,optional"`
	CorrelationId string      `json:"correlation_id,optional"`
	Detail        interface{} `json:"detail,optional"`
}

type OrdersResponse struct {
	Orders       []Order  `json:"orders"`
	Meta         ListMeta `json:"meta"`
	Status       string   `json:"status"`
	Message      string   `json:"message,omitempty"`
	ServerTimeMs int64    `json:"server_time_ms"`
}

type TraderControlRequest struct {
	TraderId       string `path:"traderId"`
	RequestedBy    string `json:"requested_by"`
	Reason         string `json:"reason"`
	IdempotencyKey string `json:"idempotency_key,optional"`
	CorrelationId  string `json:"correlation_id,optional"`
	EffectiveUntil string `json:"effective_until,optional"`
}

type TraderControlResponse struct {
	Accepted         bool   `json:"accepted"`
	Status           string `json:"status"`
	TraderId         string `json:"trader_id"`
	Action           string `json:"action"`
	CorrelationId    string `json:"correlation_id,omitempty"`
	ControlState     string `json:"control_state,omitempty"`
	ExecutionMode    string `json:"execution_mode,omitempty"`
	Queued           bool   `json:"queued"`
	ControlPlaneOnly bool   `json:"control_plane_only"`
	Message          string `json:"message,omitempty"`
	ServerTimeMs     int64  `json:"server_time_ms"`
}

type DecisionActionRequest struct {
	DecisionId     string `path:"decisionId"`
	RequestedBy    string `json:"requested_by"`
	Reason         string `json:"reason"`
	IdempotencyKey string `json:"idempotency_key,optional"`
	CorrelationId  string `json:"correlation_id,optional"`
}

type DecisionActionResponse struct {
	Accepted      bool   `json:"accepted"`
	Status        string `json:"status"`
	DecisionId    string `json:"decision_id"`
	Action        string `json:"action"`
	CorrelationId string `json:"correlation_id,omitempty"`
	Queued        bool   `json:"queued"`
	Message       string `json:"message,omitempty"`
	ServerTimeMs  int64  `json:"server_time_ms"`
}

type OrderPreviewRequest struct {
	TraderId      string                 `json:"trader_id"`
	DecisionId    string                 `json:"decision_id,optional"`
	CorrelationId string                 `json:"correlation_id,optional"`
	Orders        []Order                `json:"orders"`
	RiskContext   map[string]interface{} `json:"risk_context,optional"`
}

type OrderPreviewResponse struct {
	Accepted      bool        `json:"accepted"`
	Status        string      `json:"status"`
	PreviewId     string      `json:"preview_id,omitempty"`
	CorrelationId string      `json:"correlation_id,omitempty"`
	Checks        interface{} `json:"checks,omitempty"`
	Submitted     bool        `json:"submitted"`
	Message       string      `json:"message,omitempty"`
	ServerTimeMs  int64       `json:"server_time_ms"`
}

type OrderActionRequest struct {
	OrderId        string `path:"orderId"`
	RequestedBy    string `json:"requested_by"`
	Reason         string `json:"reason"`
	IdempotencyKey string `json:"idempotency_key,optional"`
	CorrelationId  string `json:"correlation_id,optional"`
}

type OrderActionResponse struct {
	Accepted      bool   `json:"accepted"`
	Status        string `json:"status"`
	OrderId       string `json:"order_id"`
	Action        string `json:"action"`
	CorrelationId string `json:"correlation_id,omitempty"`
	Queued        bool   `json:"queued"`
	Message       string `json:"message,omitempty"`
	ServerTimeMs  int64  `json:"server_time_ms"`
}
